/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    kotlin("jvm") version "1.3.41"
    `maven-publish`
}

repositories {
    jcenter()
}

dependencies {
    val detekt_version by extra { "1.0.0-RC16" }
    val github_cli_version by extra { "2.1.5" }

    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))

    implementation("io.gitlab.arturbosch.detekt:detekt-core:$detekt_version")
    implementation("io.gitlab.arturbosch.detekt:detekt-api:$detekt_version")
    implementation("io.gitlab.arturbosch.detekt:detekt-cli:$detekt_version")
    implementation("org.eclipse.mylyn.github:org.eclipse.egit.github.core:$github_cli_version")
}

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            groupId    = "com.github.duck8823"
            artifactId = "detekt-ci-extension"
            version    = "0.0.1-SNAPSHOT"

            from(components["java"])
        }
    }
}
