/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    kotlin("jvm") version "1.3.41"

    id("io.gitlab.arturbosch.detekt") version "1.0.0-RC16"
}

repositories {
    jcenter()
    maven(url = "https://jitpack.io")
    mavenLocal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    detektPlugins("com.github.duck8823:detekt-ci-extension:0.0.1-SNAPSHOT")
}

detekt {
    input = files("src/main/kotlin")
    config = files("detekt-config.yml")
}
