build:
  maxIssues: 0

console-reports:
  active: true
  exclude:
    - 'BuildFailureReport'
  #  - 'CircleCIBuildFailureReport'

empty-blocks:
  active: true
  EmptyDefaultConstructor:
    active: true
