build:
  maxIssues: 0

console-reports:
  active: true
  exclude:
    - 'BuildFailureReport'
    - 'CircleCIBuildFailureReport'
  #  - 'TravisCIBuildFailureReport'

empty-blocks:
  active: true
  EmptyDefaultConstructor:
    active: true
